// frontend/src/views/system/im-config/index.vue
<script setup lang="ts">
import {computed, onMounted, reactive, ref} from 'vue'
import {ElMessage, type FormInstance, type FormRules} from 'element-plus'
import {Edit, Refresh} from '@element-plus/icons-vue'
import {imConfigApi, type ImConfigDTO, type ImConfigVO} from '@/api/system/imConfig'

const loading = ref(false)
const saving = ref(false)
const dialogVisible = ref(false)
const formRef = ref<FormInstance>()
const currentPlatform = ref('')
const configList = ref<ImConfigVO[]>([])

const formData = reactive<ImConfigDTO>({
  enabled: 0,
  appId: '',
  appSecret: '',
  corpId: '',
  callbackToken: '',
  callbackAesKey: '',
  extraConfig: '{\n  "simulationMode": true,\n  "todoUrl": ""\n}',
  remark: '',
})

const rules = computed<FormRules>(() => ({
  enabled: [
    { required: true, message: '请选择启用状态', trigger: 'change' },
  ],
}))

const enabledCount = computed(() => configList.value.filter(item => item.enabled === 1).length)

async function fetchConfigs() {
  loading.value = true
  try {
    configList.value = await imConfigApi.list()
  }
  catch (error) {
    console.error('获取 IM 配置失败:', error)
    ElMessage.error('获取 IM 配置失败')
  }
  finally {
    loading.value = false
  }
}

function openEdit(row: ImConfigVO) {
  currentPlatform.value = row.platform
  Object.assign(formData, {
    enabled: row.enabled ?? 0,
    appId: row.appId ?? '',
    appSecret: row.appSecret ?? '',
    corpId: row.corpId ?? '',
    callbackToken: row.callbackToken ?? '',
    callbackAesKey: row.callbackAesKey ?? '',
    extraConfig: row.extraConfig || '{\n  "simulationMode": true,\n  "todoUrl": ""\n}',
    remark: row.remark ?? '',
  })
  dialogVisible.value = true
}

async function handleSubmit() {
  if (!formRef.value) {
    return
  }

  try {
    await formRef.value.validate()
    saving.value = true
    await imConfigApi.update(currentPlatform.value, {
      enabled: formData.enabled,
      appId: formData.appId || undefined,
      appSecret: formData.appSecret || undefined,
      corpId: formData.corpId || undefined,
      callbackToken: formData.callbackToken || undefined,
      callbackAesKey: formData.callbackAesKey || undefined,
      extraConfig: formData.extraConfig || undefined,
      remark: formData.remark || undefined,
    })
    ElMessage.success('配置已保存')
    dialogVisible.value = false
    fetchConfigs()
  }
  catch (error: unknown) {
    if (error !== false) {
      console.error('保存 IM 配置失败:', error)
      ElMessage.error('保存 IM 配置失败')
    }
  }
  finally {
    saving.value = false
  }
}

function handleDialogClose() {
  formRef.value?.resetFields()
}

onMounted(() => {
  fetchConfigs()
})
</script>

<template>
  <div class="p-4 space-y-4">
    <el-card shadow="never">
      <div class="flex flex-wrap items-center justify-between gap-3">
        <div>
          <div class="text-lg font-semibold">
            IM 平台配置
          </div>
          <div class="mt-1 text-sm text-[var(--el-text-color-secondary)]">
            当前已启用 {{ enabledCount }} / {{ configList.length }} 个审批平台。`extraConfig` 支持 `simulationMode` 与 `todoUrl`。
          </div>
        </div>
        <el-button
          :icon="Refresh"
          :loading="loading"
          @click="fetchConfigs"
        >
          刷新
        </el-button>
      </div>
    </el-card>

    <div
      v-loading="loading"
      class="grid gap-4 md:grid-cols-2 xl:grid-cols-3"
    >
      <el-card
        v-for="item in configList"
        :key="item.platform"
        shadow="hover"
        class="min-h-[280px]"
      >
        <div class="flex items-start justify-between gap-3">
          <div>
            <div class="text-base font-semibold">
              {{ item.platform }}
            </div>
            <div class="mt-1 flex flex-wrap gap-2">
              <el-tag :type="item.enabled === 1 ? 'success' : 'info'">
                {{ item.enabled === 1 ? '已启用' : '未启用' }}
              </el-tag>
              <el-tag :type="item.configReady ? 'success' : 'warning'">
                {{ item.configReady ? '配置完整' : '待补齐' }}
              </el-tag>
            </div>
          </div>
          <el-button
            type="primary"
            plain
            :icon="Edit"
            @click="openEdit(item)"
          >
            编辑
          </el-button>
        </div>

        <el-descriptions
          :column="1"
          border
          class="mt-4"
        >
          <el-descriptions-item label="App ID">
            {{ item.appId || '-' }}
          </el-descriptions-item>
          <el-descriptions-item label="Corp ID">
            {{ item.corpId || '-' }}
          </el-descriptions-item>
          <el-descriptions-item label="缺失字段">
            <template v-if="item.missingFields?.length">
              <div class="flex flex-wrap gap-2">
                <el-tag
                  v-for="field in item.missingFields"
                  :key="field"
                  type="danger"
                  effect="plain"
                >
                  {{ field }}
                </el-tag>
              </div>
            </template>
            <span v-else>-</span>
          </el-descriptions-item>
          <el-descriptions-item label="备注">
            {{ item.remark || '-' }}
          </el-descriptions-item>
        </el-descriptions>
      </el-card>
    </div>

    <el-dialog
      v-model="dialogVisible"
      :title="`编辑 ${currentPlatform} 配置`"
      width="680px"
      @closed="handleDialogClose"
    >
      <el-form
        ref="formRef"
        :model="formData"
        :rules="rules"
        label-width="128px"
      >
        <el-form-item
          label="启用状态"
          prop="enabled"
        >
          <el-radio-group v-model="formData.enabled">
            <el-radio :value="1">
              启用
            </el-radio>
            <el-radio :value="0">
              禁用
            </el-radio>
          </el-radio-group>
        </el-form-item>
        <el-form-item label="App ID">
          <el-input
            v-model="formData.appId"
            placeholder="请输入平台 App ID"
          />
        </el-form-item>
        <el-form-item label="App Secret">
          <el-input
            v-model="formData.appSecret"
            placeholder="保留现值可直接提交"
            show-password
          />
        </el-form-item>
        <el-form-item label="Corp ID">
          <el-input
            v-model="formData.corpId"
            placeholder="企业ID（企微等平台需要）"
          />
        </el-form-item>
        <el-form-item label="Callback Token">
          <el-input
            v-model="formData.callbackToken"
            placeholder="请输入回调校验 Token"
          />
        </el-form-item>
        <el-form-item label="Callback AES Key">
          <el-input
            v-model="formData.callbackAesKey"
            placeholder="请输入回调 AES Key"
          />
        </el-form-item>
        <el-form-item label="扩展配置 JSON">
          <el-input
            v-model="formData.extraConfig"
            type="textarea"
            :rows="8"
            placeholder="例如：{ &quot;simulationMode&quot;: true, &quot;todoUrl&quot;: &quot;https://...&quot; }"
          />
        </el-form-item>
        <el-form-item label="备注">
          <el-input
            v-model="formData.remark"
            type="textarea"
            :rows="3"
            placeholder="记录平台对接说明、回调地址约定等"
          />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dialogVisible = false">
          取消
        </el-button>
        <el-button
          type="primary"
          :loading="saving"
          @click="handleSubmit"
        >
          保存
        </el-button>
      </template>
    </el-dialog>
  </div>
</template>

// frontend-react/src/pages/System/ImConfig/index.tsx
/**
 * IM 平台配置
 *
 * - 卡片网格展示各审批平台（飞书/企微/钉钉）的配置状态（/system/im-config GET）。
 * - 编辑：ModalForm 更新单平台配置（/system/im-config/{platform} PUT）。
 *
 * 状态语义：enabled 1=启用，0=禁用。
 */
import { list10 as listConfigs, update5 as updateConfig } from '@/services/aiperm/imConfig';
import { PageContainer } from '@ant-design/pro-components';
import {
  ModalForm,
  ProFormSelect,
  ProFormText,
  ProFormTextArea,
} from '@ant-design/pro-components';
import { Button, Card, Col, Descriptions, Empty, Form, Row, Spin, Tag, message } from 'antd';
import React, { useCallback, useEffect, useState } from 'react';

/** 扩展配置的默认 JSON 模板 */
const DEFAULT_EXTRA_CONFIG = '{\n  "simulationMode": true,\n  "todoUrl": ""\n}';

const ImConfig: React.FC = () => {
  const [loading, setLoading] = useState(false);
  const [configList, setConfigList] = useState<API.ImConfigVO[]>([]);
  const [modalOpen, setModalOpen] = useState(false);
  const [current, setCurrent] = useState<API.ImConfigVO>();
  const [form] = Form.useForm<API.ImConfigDTO>();

  const loadConfigs = useCallback(async () => {
    setLoading(true);
    try {
      const res: any = await listConfigs();
      // RListImConfigVO 为数组包装类型，拦截器已解包到数组本身
      const list: API.ImConfigVO[] = Array.isArray(res) ? res : (res?.data ?? []);
      setConfigList(list);
    } catch {
      // 业务失败已在拦截器统一提示，这里静默兜底避免页面崩溃
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    loadConfigs();
  }, [loadConfigs]);

  const enabledCount = configList.filter((item) => item.enabled === 1).length;

  const openEdit = (row: API.ImConfigVO) => {
    setCurrent(row);
    // 异步数据需手动回填（ModalForm initialValues 仅挂载时读取一次）
    form.setFieldsValue({
      enabled: row.enabled ?? 0,
      appId: row.appId ?? '',
      appSecret: '',
      corpId: row.corpId ?? '',
      callbackToken: row.callbackToken ?? '',
      callbackAesKey: row.callbackAesKey ?? '',
      extraConfig: row.extraConfig || DEFAULT_EXTRA_CONFIG,
      remark: row.remark ?? '',
    });
    setModalOpen(true);
  };

  return (
    <PageContainer>
      <Card style={{ marginBottom: 16 }}>
        <div style={{ display: 'flex', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between', gap: 12 }}>
          <div>
            <div style={{ fontSize: 16, fontWeight: 600 }}>IM 平台配置</div>
            <div style={{ marginTop: 4, color: '#999', fontSize: 13 }}>
              当前已启用 {enabledCount} / {configList.length} 个审批平台。extraConfig 支持 simulationMode 与 todoUrl。
            </div>
          </div>
          <Button onClick={loadConfigs} loading={loading}>
            刷新
          </Button>
        </div>
      </Card>

      <Spin spinning={loading}>
        {configList.length === 0 && !loading ? (
          <Empty description="暂无平台配置" />
        ) : (
          <Row gutter={[16, 16]}>
            {configList.map((item) => (
              <Col xs={24} sm={12} lg={8} key={item.platform}>
                <Card
                  styles={{ body: { minHeight: 280 } }}
                  title={
                    <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                      <span style={{ fontWeight: 600 }}>{item.platform}</span>
                      <Tag color={item.enabled === 1 ? 'success' : 'default'}>
                        {item.enabled === 1 ? '已启用' : '未启用'}
                      </Tag>
                      <Tag color={item.configReady ? 'success' : 'warning'}>
                        {item.configReady ? '配置完整' : '待补齐'}
                      </Tag>
                    </div>
                  }
                  extra={
                    <Button type="primary" size="small" onClick={() => openEdit(item)}>
                      编辑
                    </Button>
                  }
                >
                  <Descriptions column={1} size="small">
                    <Descriptions.Item label="App ID">{item.appId || '-'}</Descriptions.Item>
                    <Descriptions.Item label="Corp ID">{item.corpId || '-'}</Descriptions.Item>
                    <Descriptions.Item label="缺失字段">
                      {item.missingFields?.length ? (
                        <span>
                          {item.missingFields.map((field) => (
                            <Tag color="error" key={field} style={{ marginBottom: 4 }}>
                              {field}
                            </Tag>
                          ))}
                        </span>
                      ) : (
                        '-'
                      )}
                    </Descriptions.Item>
                    <Descriptions.Item label="备注">{item.remark || '-'}</Descriptions.Item>
                  </Descriptions>
                </Card>
              </Col>
            ))}
          </Row>
        )}
      </Spin>

      <ModalForm
        form={form}
        title={`编辑 ${current?.platform ?? ''} 配置`}
        width={720}
        grid
        rowProps={{ gutter: 16 }}
        open={modalOpen}
        onOpenChange={setModalOpen}
        modalProps={{ destroyOnClose: true }}
        onFinish={async (values) => {
          try {
            // 空字符串字段转 undefined，避免覆盖后端已有值
            const payload: API.ImConfigDTO = {
              enabled: values.enabled,
              appId: values.appId || undefined,
              appSecret: values.appSecret || undefined,
              corpId: values.corpId || undefined,
              callbackToken: values.callbackToken || undefined,
              callbackAesKey: values.callbackAesKey || undefined,
              extraConfig: values.extraConfig || undefined,
              remark: values.remark || undefined,
            };
            await updateConfig({ platform: current?.platform ?? '' } as any, payload);
            message.success('配置已保存');
            loadConfigs();
            return true;
          } catch {
            return false;
          }
        }}
      >
        <ProFormSelect
          name="enabled"
          label="启用状态"
          colProps={{ span: 12 }}
          rules={[{ required: true, message: '请选择启用状态' }]}
          options={[
            { label: '启用', value: 1 },
            { label: '禁用', value: 0 },
          ]}
        />
        <ProFormText name="appId" label="App ID" colProps={{ span: 12 }} placeholder="请输入平台 App ID" />
        <ProFormText.Password
          name="appSecret"
          label="App Secret"
          colProps={{ span: 12 }}
          placeholder="保留现值可直接提交"
        />
        <ProFormText name="corpId" label="Corp ID" colProps={{ span: 12 }} placeholder="企业ID（企微等平台需要）" />
        <ProFormText
          name="callbackToken"
          label="Callback Token"
          colProps={{ span: 12 }}
          placeholder="请输入回调校验 Token"
        />
        <ProFormText.Password
          name="callbackAesKey"
          label="Callback AES Key"
          colProps={{ span: 12 }}
          placeholder="请输入回调 AES Key"
        />
        <ProFormTextArea
          name="extraConfig"
          label="扩展配置 JSON"
          colProps={{ span: 24 }}
          fieldProps={{ rows: 8 }}
          placeholder='例如：{ "simulationMode": true, "todoUrl": "https://..." }'
        />
        <ProFormTextArea
          name="remark"
          label="备注"
          colProps={{ span: 24 }}
          fieldProps={{ rows: 3 }}
          placeholder="记录平台对接说明、回调地址约定等"
        />
      </ModalForm>
    </PageContainer>
  );
};

export default ImConfig;
