// frontend-react/src/pages/Monitor/Server/index.tsx
/**
 * 服务监控
 *
 * - 仪表盘型页面，GET /monitor/server 返回 ServerMonitorVO。
 * - 展示应用状态、运行时长、CPU、内存/磁盘使用、运行环境、健康检查。
 *
 * 纯只读，无表单/无 CRUD。
 */
import { overview as getServer } from '@/services/aiperm/monitorServer';
import { PageContainer, ProCard, StatisticCard } from '@ant-design/pro-components';
import { Button, Col, Descriptions, Progress, Row, Spin, Table, Tag } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import React, { useCallback, useEffect, useMemo, useState } from 'react';

/** 0~1 小数 → 百分比文本 */
function formatPercent(v?: number): string {
  if (v == null || Number.isNaN(v)) return '-';
  return `${Math.round(v * 100)}%`;
}

/** 0~1 小数 → 0~100 整数（给 Progress 用） */
function toPercent(v?: number): number {
  if (v == null || Number.isNaN(v)) return 0;
  return Math.min(Math.max(Math.round(v * 100), 0), 100);
}

/** 字节 → 自适应可读大小 */
function formatBytes(v?: number): string {
  if (v == null || v <= 0 || Number.isNaN(v)) return '0 B';
  const units = ['B', 'KB', 'MB', 'GB', 'TB'];
  let idx = 0;
  let val = v;
  while (val >= 1024 && idx < units.length - 1) {
    val /= 1024;
    idx += 1;
  }
  // >=10 或最小单位取 0 位小数，否则 1 位
  const digits = val >= 10 || idx === 0 ? 0 : 1;
  return `${val.toFixed(digits)} ${units[idx]}`;
}

/** 毫秒 → 运行时长（天/时/分） */
function formatUptime(v?: number): string {
  if (v == null || v <= 0 || Number.isNaN(v)) return '-';
  const totalSec = Math.floor(v / 1000);
  const days = Math.floor(totalSec / 86400);
  const hours = Math.floor((totalSec % 86400) / 3600);
  const minutes = Math.floor((totalSec % 3600) / 60);
  if (days > 0) return `${days}天 ${hours}小时 ${minutes}分钟`;
  if (hours > 0) return `${hours}小时 ${minutes}分钟`;
  return `${minutes}分钟`;
}

/** 已用/总量 → 百分比（处理 max=0 除零） */
function usagePercent(used?: number, max?: number): number {
  if (!max || max <= 0) return 0;
  return Math.min(Math.max(Math.round(((used ?? 0) / max) * 100), 0), 100);
}

const ServerMonitor: React.FC = () => {
  const [data, setData] = useState<API.ServerMonitorVO>({});
  const [loading, setLoading] = useState(false);

  const loadData = useCallback(async () => {
    setLoading(true);
    try {
      const res: any = await getServer();
      setData((res as API.ServerMonitorVO) || {});
    } catch {
      // 业务失败已在拦截器统一提示，这里静默兜底避免页面崩溃
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    loadData();
  }, [loadData]);

  const heapPercent = useMemo(
    () => usagePercent(data.heapUsed, data.heapMax),
    [data.heapUsed, data.heapMax],
  );
  const nonHeapPercent = useMemo(
    () => usagePercent(data.nonHeapUsed, data.nonHeapMax),
    [data.nonHeapUsed, data.nonHeapMax],
  );
  const diskPercent = useMemo(() => {
    if (!data.diskTotal || data.diskTotal <= 0) return 0;
    const used = data.diskTotal - (data.diskUsable ?? 0);
    return Math.min(Math.max(Math.round((used / data.diskTotal) * 100), 0), 100);
  }, [data.diskTotal, data.diskUsable]);

  const healthColumns: ColumnsType<API.HealthComponentVO> = [
    { title: '组件', dataIndex: 'name', width: 180 },
    {
      title: '状态',
      dataIndex: 'status',
      width: 120,
      align: 'center',
      render: (status) => (
        <Tag color={status === 'UP' ? 'success' : 'error'}>{(status as string) || '-'}</Tag>
      ),
    },
    { title: '详情', dataIndex: 'details' },
  ];

  const isUp = data.status === 'UP';

  return (
    <PageContainer>
      <Spin spinning={loading}>
        <Row gutter={16}>
          <Col xs={24} sm={12} lg={6}>
            <ProCard>
              <div style={{ marginBottom: 8, color: '#999', fontSize: 13 }}>应用状态</div>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                <Tag color={isUp ? 'success' : 'error'} style={{ fontSize: 14, padding: '2px 12px' }}>
                  {data.status || '-'}
                </Tag>
                <span style={{ fontWeight: 600 }}>{data.appName || 'AIPerm'}</span>
              </div>
            </ProCard>
          </Col>
          <Col xs={24} sm={12} lg={6}>
            <StatisticCard statistic={{ title: '运行时长', value: formatUptime(data.uptime) }} />
          </Col>
          <Col xs={24} sm={12} lg={6}>
            <ProCard title="系统 CPU">
              <div style={{ marginBottom: 4 }}>{formatPercent(data.systemCpuUsage)}</div>
              <Progress percent={toPercent(data.systemCpuUsage)} size="small" />
            </ProCard>
          </Col>
          <Col xs={24} sm={12} lg={6}>
            <ProCard title="进程 CPU">
              <div style={{ marginBottom: 4 }}>{formatPercent(data.processCpuUsage)}</div>
              <Progress percent={toPercent(data.processCpuUsage)} size="small" status="success" />
            </ProCard>
          </Col>
        </Row>

        <Row gutter={16} style={{ marginTop: 16 }}>
          <Col xs={24} lg={14}>
            <ProCard
              title="资源使用"
              extra={
                <Button onClick={loadData} loading={loading}>
                  刷新
                </Button>
              }
            >
              <div style={{ marginBottom: 16 }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 4 }}>
                  <span>堆内存</span>
                  <span style={{ color: '#999' }}>
                    {formatBytes(data.heapUsed)} / {formatBytes(data.heapMax)}
                  </span>
                </div>
                <Progress percent={heapPercent} size="small" />
              </div>
              <div style={{ marginBottom: 16 }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 4 }}>
                  <span>非堆内存</span>
                  <span style={{ color: '#999' }}>
                    {formatBytes(data.nonHeapUsed)} / {formatBytes(data.nonHeapMax)}
                  </span>
                </div>
                <Progress percent={nonHeapPercent} size="small" status="success" />
              </div>
              <div>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 4 }}>
                  <span>磁盘使用</span>
                  <span style={{ color: '#999' }}>
                    {formatBytes((data.diskTotal ?? 0) - (data.diskUsable ?? 0))} /{' '}
                    {formatBytes(data.diskTotal)}
                  </span>
                </div>
                <Progress percent={diskPercent} size="small" status="active" strokeColor="#faad14" />
              </div>
            </ProCard>
          </Col>
          <Col xs={24} lg={10}>
            <ProCard title="运行环境">
              <Descriptions column={1} size="small" bordered>
                <Descriptions.Item label="环境">
                  {data.activeProfiles?.length ? data.activeProfiles.join(', ') : 'default'}
                </Descriptions.Item>
                <Descriptions.Item label="Java">{data.javaVersion || '-'}</Descriptions.Item>
                <Descriptions.Item label="操作系统">{data.osName || '-'}</Descriptions.Item>
                <Descriptions.Item label="CPU 核数">{data.processors ?? '-'}</Descriptions.Item>
                <Descriptions.Item label="线程">
                  活动 {data.liveThreads ?? '-'} / 守护 {data.daemonThreads ?? '-'} / 峰值{' '}
                  {data.peakThreads ?? '-'}
                </Descriptions.Item>
              </Descriptions>
            </ProCard>
          </Col>
        </Row>

        <ProCard title="健康检查" style={{ marginTop: 16 }}>
          <Table<API.HealthComponentVO>
            rowKey="name"
            size="small"
            columns={healthColumns}
            dataSource={data.healthComponents || []}
            pagination={false}
            locale={{ emptyText: '暂无健康检查数据' }}
          />
        </ProCard>
      </Spin>
    </PageContainer>
  );
};

export default ServerMonitor;

// frontend/src/views/monitor/server/index.vue
<script setup lang="ts">
import {computed, onMounted, ref} from 'vue'
import {ElMessage} from 'element-plus'
import {Refresh} from '@element-plus/icons-vue'
import {serverMonitorApi, type ServerMonitorVO} from '@/api/monitor'

const loading = ref(false)
const overview = ref<ServerMonitorVO | null>(null)

function formatPercent(value?: number) {
  return `${Math.round((value ?? 0) * 100)}%`
}

function toPercent(value?: number) {
  return Math.min(100, Math.max(0, Math.round((value ?? 0) * 100)))
}

function formatBytes(value?: number) {
  const size = value ?? 0
  if (size <= 0) {
    return '0 B'
  }
  const units = ['B', 'KB', 'MB', 'GB', 'TB']
  let current = size
  let index = 0
  while (current >= 1024 && index < units.length - 1) {
    current /= 1024
    index++
  }
  return `${current.toFixed(current >= 10 || index === 0 ? 0 : 1)} ${units[index]}`
}

function formatUptime(value?: number) {
  const totalSeconds = Math.floor((value ?? 0) / 1000)
  const days = Math.floor(totalSeconds / 86400)
  const hours = Math.floor((totalSeconds % 86400) / 3600)
  const minutes = Math.floor((totalSeconds % 3600) / 60)
  if (days > 0) {
    return `${days}天 ${hours}小时 ${minutes}分钟`
  }
  if (hours > 0) {
    return `${hours}小时 ${minutes}分钟`
  }
  return `${minutes}分钟`
}

const heapUsage = computed(() => {
  if (!overview.value?.heapMax) {
    return 0
  }
  return (overview.value.heapUsed / overview.value.heapMax) * 100
})

const nonHeapUsage = computed(() => {
  if (!overview.value?.nonHeapMax) {
    return 0
  }
  return (overview.value.nonHeapUsed / overview.value.nonHeapMax) * 100
})

const diskUsage = computed(() => {
  if (!overview.value?.diskTotal) {
    return 0
  }
  return ((overview.value.diskTotal - overview.value.diskUsable) / overview.value.diskTotal) * 100
})

async function fetchOverview() {
  loading.value = true
  try {
    overview.value = await serverMonitorApi.getOverview()
  }
  catch (error) {
    console.error('获取服务监控失败:', error)
    ElMessage.error('获取服务监控失败')
  }
  finally {
    loading.value = false
  }
}

onMounted(() => {
  fetchOverview()
})
</script>

<template>
  <div class="p-4">
    <div class="mb-4 flex items-center justify-between">
      <div>
        <div class="text-lg font-semibold">
          服务监控
        </div>
        <div class="text-sm text-gray-500">
          查看应用运行状态、资源占用和健康检查明细
        </div>
      </div>
      <el-button
        :icon="Refresh"
        v-permission="'monitor:server:list'"
        @click="fetchOverview"
      >
        刷新
      </el-button>
    </div>

    <div
      v-loading="loading"
      class="grid gap-4"
    >
      <el-row :gutter="16">
        <el-col
          :xs="24"
          :sm="12"
          :lg="6"
        >
          <el-card>
            <div class="text-sm text-gray-500">
              应用状态
            </div>
            <div class="mt-3 flex items-center gap-2">
              <el-tag :type="overview?.status === 'UP' ? 'success' : 'danger'">
                {{ overview?.status || '-' }}
              </el-tag>
              <span class="text-sm">{{ overview?.appName || 'AIPerm' }}</span>
            </div>
          </el-card>
        </el-col>
        <el-col
          :xs="24"
          :sm="12"
          :lg="6"
        >
          <el-card>
            <div class="text-sm text-gray-500">
              运行时长
            </div>
            <div class="mt-3 text-xl font-semibold">
              {{ formatUptime(overview?.uptime) }}
            </div>
          </el-card>
        </el-col>
        <el-col
          :xs="24"
          :sm="12"
          :lg="6"
        >
          <el-card>
            <div class="text-sm text-gray-500">
              系统 CPU
            </div>
            <div class="mt-3 text-xl font-semibold">
              {{ formatPercent(overview?.systemCpuUsage) }}
            </div>
            <el-progress
              class="mt-3"
              :percentage="toPercent(overview?.systemCpuUsage)"
              :stroke-width="8"
            />
          </el-card>
        </el-col>
        <el-col
          :xs="24"
          :sm="12"
          :lg="6"
        >
          <el-card>
            <div class="text-sm text-gray-500">
              进程 CPU
            </div>
            <div class="mt-3 text-xl font-semibold">
              {{ formatPercent(overview?.processCpuUsage) }}
            </div>
            <el-progress
              class="mt-3"
              :percentage="toPercent(overview?.processCpuUsage)"
              :stroke-width="8"
              status="success"
            />
          </el-card>
        </el-col>
      </el-row>

      <el-row :gutter="16">
        <el-col
          :xs="24"
          :lg="14"
        >
          <el-card>
            <template #header>
              <div class="font-medium">
                资源使用
              </div>
            </template>
            <div class="grid gap-4">
              <div>
                <div class="mb-2 flex items-center justify-between text-sm">
                  <span>堆内存</span>
                  <span>{{ formatBytes(overview?.heapUsed) }} / {{ formatBytes(overview?.heapMax) }}</span>
                </div>
                <el-progress
                  :percentage="Math.round(heapUsage)"
                  :stroke-width="10"
                />
              </div>
              <div>
                <div class="mb-2 flex items-center justify-between text-sm">
                  <span>非堆内存</span>
                  <span>{{ formatBytes(overview?.nonHeapUsed) }} / {{ formatBytes(overview?.nonHeapMax) }}</span>
                </div>
                <el-progress
                  :percentage="Math.round(nonHeapUsage)"
                  :stroke-width="10"
                  status="success"
                />
              </div>
              <div>
                <div class="mb-2 flex items-center justify-between text-sm">
                  <span>磁盘使用</span>
                  <span>{{ formatBytes((overview?.diskTotal ?? 0) - (overview?.diskUsable ?? 0)) }} / {{ formatBytes(overview?.diskTotal) }}</span>
                </div>
                <el-progress
                  :percentage="Math.round(diskUsage)"
                  :stroke-width="10"
                  status="warning"
                />
              </div>
            </div>
          </el-card>
        </el-col>
        <el-col
          :xs="24"
          :lg="10"
        >
          <el-card>
            <template #header>
              <div class="font-medium">
                运行环境
              </div>
            </template>
            <el-descriptions
              :column="1"
              border
            >
              <el-descriptions-item label="环境">
                {{ overview?.activeProfiles?.join(', ') || 'default' }}
              </el-descriptions-item>
              <el-descriptions-item label="Java">
                {{ overview?.javaVersion || '-' }}
              </el-descriptions-item>
              <el-descriptions-item label="操作系统">
                {{ overview?.osName || '-' }}
              </el-descriptions-item>
              <el-descriptions-item label="CPU 核数">
                {{ overview?.processors ?? 0 }}
              </el-descriptions-item>
              <el-descriptions-item label="线程">
                活动 {{ overview?.liveThreads ?? 0 }} / 守护 {{ overview?.daemonThreads ?? 0 }} / 峰值 {{ overview?.peakThreads ?? 0 }}
              </el-descriptions-item>
            </el-descriptions>
          </el-card>
        </el-col>
      </el-row>

      <el-card>
        <template #header>
          <div class="font-medium">
            健康检查
          </div>
        </template>
        <el-table
          :data="overview?.healthComponents || []"
          empty-text="暂无健康检查数据"
        >
          <el-table-column
            prop="name"
            label="组件"
            min-width="160"
          />
          <el-table-column
            label="状态"
            width="120"
            align="center"
          >
            <template #default="{ row }">
              <el-tag :type="row.status === 'UP' ? 'success' : 'danger'">
                {{ row.status }}
              </el-tag>
            </template>
          </el-table-column>
          <el-table-column
            prop="details"
            label="详情"
            min-width="260"
            show-overflow-tooltip
          />
        </el-table>
      </el-card>
    </div>
  </div>
</template>
